name: CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  BuildAndPreRelease:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      SolutionName: Paulov.Tarkov.LogRedirector
      ProjectClient: Paulov.Tarkov.LogRedirector.csproj
      DllName: Paulov.Tarkov.LogRedirector

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
          fetch-depth: 0
          
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
   
      # Restore all projects
      - name: dotnet Restore
        run: dotnet restore

       # Build the project
      - name: Build
        run: |
          dotnet build ${{ env.ProjectClient }} -c Release -o ${{ env.DllName }}

      - name: Get version from DLL
        id: extract-version
        shell: pwsh
        run: |
          $v = $([System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm"))
          echo $v
          echo VERSION=$v >> $env:GITHUB_OUTPUT

      - name: Display Version in Logs
        run: echo "The extracted version is ${{ steps.extract-version.outputs.VERSION }}"
  
      - name: Zip remaining files
        shell: pwsh
        run: |
            Compress-Archive -Path "${{ env.DllName }}\${{ env.DllName }}.dll" -DestinationPath ${{ env.DllName }}.zip
   
      # Create release as draft from the compressed file
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
            generate_release_notes: true
            files: ${{ env.DllName }}.zip
            token: ${{ secrets.PAT_KEY }}
            tag_name: ${{ env.DllName }}-${{ steps.extract-version.outputs.VERSION }}
